### ISSUE TITLE
ImportError: No module named jinja2

### ISSUE THREAD

**Issue by markcocker** [vince-stark/keepass-to-1password#3]
II get the error `ImportError: No module named jinja2` when running k1p.py despite jinja2 being installed.

```
pip install beautifulsoup4
Requirement already satisfied: beautifulsoup4 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (4.7.1)
Requirement already satisfied: soupsieve>=1.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from beautifulsoup4) (1.8)

pip install jinja2
Requirement already satisfied: jinja2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (2.10)
Requirement already satisfied: MarkupSafe>=0.23 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from jinja2) (1.1.1)

./k1p.py
Traceback (most recent call last):
  File "./k1p.py", line 8, in <module>
    from jinja2 import Environment, PackageLoader
ImportError: No module named jinja2
```

**Comment by vince-stark** [comment]
@markcocker please try the latest `master` and do `pip install -r requirements.txt`

**Comment by markcocker** [comment]
Same results...
```
cockerma@Marks-MacBook-Pro:~/git/keepass-to-1password$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
cockerma@Marks-MacBook-Pro:~/git/keepass-to-1password$ pip install -r requirements.txt
Requirement already satisfied: beautifulsoup4==4.7.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (4.7.1)
Requirement already satisfied: Jinja2==2.10 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (2.10)
Requirement already satisfied: soupsieve>=1.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from beautifulsoup4==4.7.1->-r requirements.txt (line 1)) (1.8)
Requirement already satisfied: MarkupSafe>=0.23 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from Jinja2==2.10->-r requirements.txt (line 2)) (1.1.1)
cockerma@Marks-MacBook-Pro:~/git/keepass-to-1password$ ./k1p.py
INFO:k1p:KeePass XML file is opened
Traceback (most recent call last):
  File "./k1p.py", line 121, in <module>
    output.write(template.render(passwords=passwords).encode('utf-8'))
TypeError: write() argument must be str, not bytes
cockerma@Marks-MacBook-Pro:~/git/keepass-to-1password$ date
Fri 15 Mar 2019 17:54:20 MST
```
